[package]
name = "pistol"
version = "0.1.4"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
piston_window = "0.47.0"
pistoncore-sdl2_window = "0.30.2"
image = "0.10.0"
scoped_threadpool = "0.1.7"
fnv = "1.0.2"
num_cpus = "0.2.12"
