[package]
name = "pistol"
version = "0.1.2"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
piston_window = "0.43.0"
image = "0.9.0"
scoped_threadpool = "0.1.7"
fnv = "1.0.2"
num_cpus = "0.2.11"
